theme: jekyll-theme-hacker
title: Welkome to rootjenna's homepage!
description: I have been coding for a few years. First I started wit Linux bash scripts and sql database. 
 
I try to share my experiense of the bash here in GitHub. Hope I can help!   
